#!/bin/bash
XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}

# Allow users to override command-line options
if [[ -f $XDG_CONFIG_HOME/code-flags.conf ]]; then
   SPOTIFY_USER_FLAGS="$(sed 's/#.*//' $XDG_CONFIG_HOME/spotify-flags.conf | tr '\n' ' ')"
fi

# Launch Spotify with the given flags
exec /opt/spotify/spotify $SPOTIFY_USER_FLAGS

